apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
data:
  mysql_root_host: '%'
  mysql_database: testdb
  mysql_user: quarkus
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
data:
  password: LW4gJ3Bhc3N3b3JkJyANCg==
  quarkus_password: cXVhcmt1cwo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-config
                  key: mysql_root_host
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-config
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-config
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: quarkus_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
